"""
HLSKey ORM model.

Stores the AES-128 encryption key used for HLS segment encryption.
There is exactly one HLSKey per Movie (enforced by UNIQUE constraint on movie_id).

Security model:
- The raw 16-byte key is generated by the uploader during FFmpeg processing.
- It is encrypted with our AES-256-GCM master key before storage.
- The backend decrypts it on demand when serving GET /api/playback/hls-key.
- B2 stores only encrypted segments — useless without the key from this table.

The IV (Initialization Vector) is stored as a 32-character hex string
(16 bytes = 32 hex chars). It is included in the HLS playlist's EXT-X-KEY tag.
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    import uuid

    from app.models.movie import Movie


class HLSKey(Base, UUIDPrimaryKeyMixin):
    """AES-128 encryption key for a single Movie's HLS stream."""

    __tablename__ = "hls_keys"

    # ── Foreign key ───────────────────────────────────────────────────────────
    # unique=True enforces the 1:1 relationship with Movie
    movie_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("movies.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
    )

    # ── Encrypted key ─────────────────────────────────────────────────────────
    # Plaintext: 16-byte AES-128 key, hex-encoded (32 chars).
    # Stored as: AES-256-GCM(nonce + ciphertext), base64url-encoded.
    key_encrypted: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="AES-256-GCM encrypted 16-byte HLS key. NEVER expose in responses.",
    )

    # ── Initialization vector ─────────────────────────────────────────────────
    # 16 bytes = 32 hex chars. Included in the HLS playlist EXT-X-KEY tag.
    # The IV is NOT secret (it is embedded in the playlist), only the key is.
    iv_hex: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        comment="16-byte IV as a 32-char hex string. Included in HLS playlist.",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    movie: Mapped[Movie] = relationship(
        "Movie",
        back_populates="hls_key",
        lazy="select",
    )

    def __repr__(self) -> str:
        return f"<HLSKey id={self.id} movie_id={self.movie_id}>"
