"""Initial schema

Revision ID: d8720b47c441
Revises: 
Create Date: 2026-07-12 16:59:34.590645

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8720b47c441'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('LEVEL1', 'LEVEL2', 'SUPER_ADMIN', name='userrole', native_enum=False, length=20), server_default='level1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('storage_providers',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.Enum('B2', 'R2', 'S3', 'MINIO', name='storageprovidertype', native_enum=False, length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Human-readable label shown in the UI, e.g. 'My B2 Movies Bucket'"),
    sa.Column('credentials_encrypted', sa.Text(), nullable=False, comment='AES-256-GCM encrypted JSON credentials. NEVER expose in responses.'),
    sa.Column('bucket_name', sa.String(length=255), nullable=False),
    sa.Column('endpoint_url', sa.String(length=512), nullable=True, comment='S3-compatible endpoint URL. e.g. https://s3.us-west-004.backblazeb2.com'),
    sa.Column('cdn_url', sa.String(length=512), nullable=True, comment='CDN origin URL e.g. https://cdn.example.com — served to clients'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_storage_providers_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storage_providers'))
    )
    with op.batch_alter_table('storage_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storage_providers_owner_id'), ['owner_id'], unique=False)

    op.create_table('libraries',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('storage_provider_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_libraries_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_provider_id'], ['storage_providers.id'], name=op.f('fk_libraries_storage_provider_id_storage_providers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_libraries'))
    )
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_libraries_owner_id'), ['owner_id'], unique=False)

    op.create_table('collections',
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=512), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'FRIENDS', 'SHARED', name='visibility', native_enum=False, length=10), server_default='private', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_collections_library_id_libraries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections'))
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_library_id'), ['library_id'], unique=False)

    op.create_table('movies',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), server_default='0', nullable=False),
    sa.Column('hls_master_path', sa.String(length=512), nullable=True, comment='e.g. movies/uuid/master.m3u8'),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True, comment='Still frame thumbnail for list views'),
    sa.Column('poster_path', sa.String(length=512), nullable=True, comment='Portrait poster image'),
    sa.Column('backdrop_path', sa.String(length=512), nullable=True, comment='Wide backdrop image for movie detail page'),
    sa.Column('timeline_sprite_path', sa.String(length=512), nullable=True, comment='WebVTT + JPEG sprite for seek bar thumbnail preview'),
    sa.Column('visibility_override', sa.Enum('PRIVATE', 'FRIENDS', 'SHARED', name='visibility', native_enum=False, length=10), nullable=True),
    sa.Column('codec', sa.String(length=50), nullable=True, comment='Video codec: h264, h265, av1, vp9'),
    sa.Column('resolution_width', sa.Integer(), nullable=True),
    sa.Column('resolution_height', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('audio_tracks', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('subtitle_tracks', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('chapters', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('enriched_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_uploaded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_movies_collection_id_collections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movies'))
    )
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movies_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movies_slug'), ['slug'], unique=True)

    op.create_table('hls_keys',
    sa.Column('movie_id', sa.UUID(), nullable=False),
    sa.Column('key_encrypted', sa.Text(), nullable=False, comment='AES-256-GCM encrypted 16-byte HLS key. NEVER expose in responses.'),
    sa.Column('iv_hex', sa.String(length=32), nullable=False, comment='16-byte IV as a 32-char hex string. Included in HLS playlist.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_hls_keys_movie_id_movies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hls_keys')),
    sa.UniqueConstraint('movie_id', name=op.f('uq_hls_keys_movie_id'))
    )
    op.create_table('permissions',
    sa.Column('grantee_id', sa.UUID(), nullable=False),
    sa.Column('granted_by_id', sa.UUID(), nullable=False),
    sa.Column('library_id', sa.UUID(), nullable=True),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('movie_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(library_id, collection_id, movie_id) = 1', name=op.f('ck_permissions_ck_permissions_exactly_one_target')),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_permissions_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], name=op.f('fk_permissions_granted_by_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grantee_id'], ['users.id'], name=op.f('fk_permissions_grantee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], name=op.f('fk_permissions_library_id_libraries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_permissions_movie_id_movies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_grantee_id'), ['grantee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_movie_id'), ['movie_id'], unique=False)

    op.create_table('rooms',
    sa.Column('slug', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('movie_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Enum('WAITING', 'PLAYING', 'PAUSED', 'ENDED', name='roomstate', native_enum=False, length=10), server_default='waiting', nullable=False),
    sa.Column('position_seconds', sa.Float(), server_default='0', nullable=False),
    sa.Column('speed', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_rooms_creator_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_rooms_movie_id_movies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms'))
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_movie_id'), ['movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_slug'), ['slug'], unique=True)

    op.create_table('chat_messages',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment="For TEXT: message text. For EMOJI_REACTION: emoji char. For TIMESTAMP_SHARE: human-readable label e.g. '1:23:45'."),
    sa.Column('message_type', sa.Enum('TEXT', 'EMOJI_REACTION', 'TIMESTAMP_SHARE', name='messagetype', native_enum=False, length=20), server_default='text', nullable=False),
    sa.Column('timestamp_reference', sa.Float(), nullable=True, comment='Playback position in seconds for TIMESTAMP_SHARE messages.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_chat_messages_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_room_id'), ['room_id'], unique=False)

    op.create_table('invites',
    sa.Column('token', sa.String(length=1024), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), server_default='1', nullable=False),
    sa.Column('use_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], name=op.f('fk_invites_invited_by_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_invites_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites'))
    )
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invites_invited_by_id'), ['invited_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invites_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invites_token'), ['token'], unique=True)

    op.create_table('room_members',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_host', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_members_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_room_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id', name=op.f('pk_room_members'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_members')
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invites_token'))
        batch_op.drop_index(batch_op.f('ix_invites_room_id'))
        batch_op.drop_index(batch_op.f('ix_invites_invited_by_id'))

    op.drop_table('invites')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_room_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_slug'))
        batch_op.drop_index(batch_op.f('ix_rooms_movie_id'))

    op.drop_table('rooms')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_movie_id'))
        batch_op.drop_index(batch_op.f('ix_permissions_library_id'))
        batch_op.drop_index(batch_op.f('ix_permissions_grantee_id'))
        batch_op.drop_index(batch_op.f('ix_permissions_collection_id'))

    op.drop_table('permissions')
    op.drop_table('hls_keys')
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movies_slug'))
        batch_op.drop_index(batch_op.f('ix_movies_collection_id'))

    op.drop_table('movies')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_library_id'))

    op.drop_table('collections')
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_libraries_owner_id'))

    op.drop_table('libraries')
    with op.batch_alter_table('storage_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_providers_owner_id'))

    op.drop_table('storage_providers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
